created endpoint for create Submission
boolean-uk/team-dev-server pull request #195
Opened 2022-07-12 15:43 UTC by d-username

--> created endpoint for creating Submission
--> added a little update to Schema - "UpdatedAt"
--> tested with Insomnia

2022-07-12 15:44 UTC, d-username commented
#160    Issue number

2022-07-13 08:55 UTC, dearshrewdwit requested changes
Nice.

2022-07-13 08:55 UTC, dearshrewdwit commented on prisma/schema.prisma
> +  updatedAt        DateTime       @updatedAt
Nice catch.

2022-07-13 08:55 UTC, dearshrewdwit commented on src/controllers/user.js
> +  console.log(newSubmissionData)
Remove debugging statement

2022-07-13 08:55 UTC, dearshrewdwit commented on src/controllers/user.js
> +export const submitExercise = async (req, res) => {
Rename method to `createSubmission`

2022-07-13 09:58 UTC, dearshrewdwit approved these changes

2022-07-13 10:21 UTC, merged