Tta fix patch cohort/id
boolean-uk/team-dev-server pull request #254
Opened 2022-09-21 11:52 UTC by deliailu27

2022-09-21 11:56 UTC, vherus requested changes

2022-09-21 11:56 UTC, vherus commented on src/domain/cohort.js
> +  console.log('name', name)
Let's keep debug logs out of `main`

2022-09-21 12:04 UTC, hubertlemczak approved these changes

2022-09-21 12:04 UTC, hubertlemczak commented on src/controllers/cohort.js
>    const Id = parseInt(req.params.id)
capital letter in `Id`

2022-09-21 14:57 UTC, vherus approved these changes

2022-09-22 08:49 UTC, hubertlemczak approved these changes

2022-09-22 08:49 UTC, merged